version: '3'

tasks:
  install:
    cmds:
      - brew install act
      - npm install

  build:
    desc: Bundle index.js into dist/ using ncc.
    cmds:
      - npm run build

  test:unit:
    desc: Run unit tests.
    cmds:
      - npm test

  test:integration:
    desc: Run all integration tests.
    cmds:
      - task: test:integration:identical

  test:integration:identical:
    desc: Test status=identical (current branch is main)
    cmds:
      - act push -W .github/workflows/test.yml
