##
# TODO: "Each repository must not contain any workflow files." - This guideline is unclear, how test workflow can be run by end-user? Does this mean custom GitHub Action literally can NOT contain workflow files just for its ownn testign purposes?
# - https://docs.github.com/en/actions/how-tos/create-and-publish-actions/publish-in-github-marketplace
##

name: CD

on:
  push:
    branches: [main]

jobs:
  create_github_release:
    runs-on: ubuntu-24.04
    name: Create GitHub Release PR
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          changelog-path: CHANGELOG.md
          default-branch: main
          include-v-in-tag: true
          package-name: ensure-source-branch-contains-destination-branch
          release-type: node
          version-file: package.json
