name: CD

on:
  push:
    branches: [main]

jobs:
  create_github_release:
    runs-on: ubuntu-24.04
    name: Create GitHub Release PR
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          changelog-path: CHANGELOG.md
          default-branch: main
          include-v-in-tag: true
          package-name: ensure-source-branch-contains-destination-branch
          release-type: node
          version-file: package.json
