##
# TODO: Clarify Marketplace guideline "repository must not contain any workflow files" — does it apply to test workflows too?
# - https://docs.github.com/en/actions/how-tos/create-and-publish-actions/publish-in-github-marketplace
##

name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run format:verify
      - run: npm run lint
      - run: npm run test
      - run: npm run build:verify
